
<h3> Editando Cliente </h3>
<br/>


<?php 
$form = $this->form;

$form->setAttribute('action',$this->url('pc_helpAdmin-interna',array('controller'=>'clientes','action'=>'edit')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nome'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();



?>